### ISSUE TITLE
download raw data from google-docs

### ISSUE THREAD

**Issue by Michal-Koeckeis-Fresel** [refugee-phrasebook/refugee-phrasebook.github.io#18]
downloading data is implemented in a branch
https://github.com/refugee-phrasebook/refugee-phrasebook.github.io/pull/17/files

the script scripts/01_download.sh is fetching files from google-docs and saves them as .TSV (tab delimited) in directory download/tsv/

CSV is possible too

> Pull-Request is open

**Comment by Glottotopia** [comment]
there seems to be some duplication with https://github.com/refugee-phrasebook/py_rpb 

Please check with @amatthies

**Comment by Michal-Koeckeis-Fresel** [comment]
YES it IS duplicate ... 

one using python the other one using bash-shell - both wanting results.

not being able to commit the work leads to duplicate work.

**Comment by Glottotopia** [comment]
can we close this as this now concerns another repo @michal-fre ?

**Comment by osg** [comment]
+1

**Comment by Michal-Koeckeis-Fresel** [comment]
me too :)
