### ISSUE TITLE
Write-Access for developers

### ISSUE THREAD

**Issue by Michal-Koeckeis-Fresel** [refugee-phrasebook/refugee-phrasebook.github.io#19]
to speed up new releases it is important that some developers get write access.

otherwise different people are working on the same issues

release often + release early

code should find it's way to the project and not queue up in a mailbox

**Comment by Glottotopia** [comment]
this repo is actually the code being served by github.io, not the code one could run on one's own computers. 
To get a cleaner structure, I have created a repo https://github.com/refugee-phrasebook/backendscripts, where additional code can be shared. 
I have given write access to the Backend team, and I have added you to that team
HTH
S

**Comment by Michal-Koeckeis-Fresel** [comment]
Please review the permissions:

git tells me:
You may not have permission to access backendscripts. Check Preferences to make sure you’re still logged in.

remote: Permission to refugee-phrasebook/backendscripts.git denied to michal-fre.
fatal: unable to access 'https://github.com/refugee-phrasebook/backendscripts.git/': The requested URL returned error: 403

**Comment by Michal-Koeckeis-Fresel** [comment]
sorry - my fault - forgot to press the link in the invitation :)
