### ISSUE TITLE
Localize "Showing [1] to [100] of [180] entries" string

### ISSUE THREAD

**Issue by osg** [refugee-phrasebook/refugee-phrasebook.github.io#26]
![screenshot from 2015-10-05 21 07 16](https://cloud.githubusercontent.com/assets/1639324/10290632/91fcf524-6ba5-11e5-98df-20d719a64de9.png)

**Comment by Glottotopia** [comment]
this is now language independent, "21-30 / 154". Is this sufficient to close @opensourcegrrrl ?

**Comment by osg** [comment]
+1
