### ISSUE TITLE
Replace "poor man's" differentiaters  in language drop-down menu

### ISSUE THREAD

**Issue by osg** [refugee-phrasebook/refugee-phrasebook.github.io#29]
![screenshot from 2015-10-05 21 34 40](https://cloud.githubusercontent.com/assets/1639324/10291229/0cbf0a24-6ba9-11e5-8609-e1bc3e4b92eb.png)

**Comment by Glottotopia** [comment]
fixed this by using iso639-3 internally and full language names as labels
