### ISSUE TITLE
Is this file necessary?

### ISSUE THREAD

**Issue by osg** [refugee-phrasebook/refugee-phrasebook.github.io#8]
@Glottotopia, is the following file necessary or checked in accident:
https://github.com/refugee-phrasebook/refugee-phrasebook.github.io/blob/master/import/.simpleinput.csv.kate-swp

**Comment by Glottotopia** [comment]
no, it can be deleted. There are a couple of other files which can be deleted as well, which are remainders of former, erroneous attempts. I will get to this only Wednesday
